default-execution-mode: REACT
allow-mcps: ["meeting-server", "contacts-server"]
allow-sub-agents: []
allow-skills: ["meeting-skill"]
hooks:
  pre-tool-call:
    - bean: toolConfirmHook
      enabled: true
      order: 100
      tools: ["contacts_get_detail"]
      options:
        title: "个人信息查询"
        description: "查询个人信息查询。"
        tool-display-name: "通讯录助手"
        confirm-label: "确认执行"
        deny-label: "取消"
        display-fields:
          - key: target_user_id
            label: "用户ID"
        editable-fields:
          - key: target_user_id
            label: "用户ID"
            input-type: "single-select"
            required: true
            options:
              - label: "12345"
              - label: "12346"
  post-tool-call:
    - bean: plainTextTruncateHook
      enabled: true
      order: 200
      tools: ["*"]
      options:
        max-length: 4000
