package org.gemo.apex.runtime.definition;
import org.gemo.apex.common.agent.*;import org.gemo.apex.common.json.JsonUtils;import org.gemo.apex.extension.definition.AgentDefinitionProvider;import org.yaml.snakeyaml.Yaml;import java.io.*;import java.net.URI;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.util.*;
public final class FileAgentDefinitionProvider implements AgentDefinitionProvider{
 private final Map<String,AgentDefinition> values;
 public FileAgentDefinitionProvider(URI uri){this(uri,Thread.currentThread().getContextClassLoader());}
 public FileAgentDefinitionProvider(URI uri,ClassLoader loader){try(var r=new InputStreamReader(open(uri,loader),StandardCharsets.UTF_8)){Map<?,?> root=new Yaml().load(r);Map<?,?> agents=(Map<?,?>)root.get("agents");if(agents==null||agents.isEmpty())throw new IllegalArgumentException("agents 不能为空");Map<String,AgentDefinition> out=new LinkedHashMap<>();for(var e:agents.entrySet()){var d=JsonUtils.mapperCopy().convertValue(e.getValue(),AgentDefinition.class);if(!e.getKey().equals(d.metadata().agentKey()))throw new IllegalArgumentException("agentKey 不一致");if(out.putIfAbsent((String)e.getKey(),d)!=null)throw new IllegalArgumentException("agentKey 重复");}values=Map.copyOf(out);}catch(Exception e){throw new IllegalArgumentException("加载 Agent YAML 失败: "+uri,e);}}
 private static InputStream open(URI u,ClassLoader l)throws IOException{if("file".equals(u.getScheme()))return Files.newInputStream(Path.of(u));if("classpath".equals(u.getScheme())){var in=l.getResourceAsStream(u.getSchemeSpecificPart().replaceFirst("^/",""));if(in!=null)return in;}throw new FileNotFoundException(u.toString());}
 public AgentDefinition load(String k){var v=values.get(k);if(v==null)throw new IllegalArgumentException("Agent 不存在: "+k);return v;}public List<AgentMetadata> listAgents(){return values.values().stream().map(AgentDefinition::metadata).toList();}
}
